# Imports

In [1]:
import requests
from bs4 import BeautifulSoup
import regex as re
import pandas as pd

# Proof of Concept

In [ ]:
r = requests.get("https://mtgtop8.com/format?f=ST&meta=46&cp=2")
print(r.status_code)

In [ ]:
soup = BeautifulSoup(r.content)
event_table = soup.find_all("table")[2]   # third table on page
event_table

In [ ]:
# get the event links
event_links_raw = re.findall("<a href=.+?>", str(event_table))
event_links_clean = [link.split("\"")[1] for link in event_links_raw]
event_links_clean

In [ ]:
# get the event name and date, not sure how i want to structure this atm 
events_raw = event_table.get_text()
events = re.split("\\n{3,4}", events_raw)[1:]
for event in events:
    event_name, event_date = re.split("\\n{2}", event)[:2]
    print(event_name, '\t', event_date)
#
# [re.split("\\n{2}", event)[:2] for event in events]

# Getting All Tournaments

Tournaments for the last two months are listed 20 at a time across 6 pages, so we need to get tournaments table on each of these pages.

In [2]:
# get all tournaments html
tournaments_tables = []
for page in range(1, 7):
    r = requests.get(f"https://mtgtop8.com/format?f=ST&meta=46&cp={page}")
    if r.status_code != 200:
        print(f"Could not scrape events from page {page}.")
        continue
    #

    soup = BeautifulSoup(r.content)
    tournaments_tables.append(soup.find_all("table")[2])   # third table on page 
#
display(tournaments_tables)

[<table align="center" border="0" class="Stable" width="98%">
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80372&amp;f=ST">MTGO Challenge 32</a> <span class="new">NEW</span></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">13/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80328&amp;f=ST">MTGO Challenge 32</a> <span class="new">NEW</span></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">12/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80293&amp;f=ST">MTGO Challenge 32</a> <span class="new">NEW</span></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">10/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80250&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">09/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80147&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">08/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=80087&amp;f=ST">RCQ</a> @ <a class="und" href="event?e=80087&amp;f=ST">Playtime (Merate, Italy)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">08/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80126&amp;f=ST">MTGO Showcase Challenge</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">07/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80125&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">07/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80046&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">07/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80065&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">06/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=80029&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">06/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79976&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">05/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79952&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">03/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79924&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">02/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79877&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">01/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79818&amp;f=ST">RCQ</a> @ <a class="und" href="event?e=79818&amp;f=ST">Draco Hobby Center (Bogota, Colombia)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">01/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79819&amp;f=ST">MTGO RC Super Qualifier</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">01/02/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79854&amp;f=ST">2nd Chance PTQ</a> @ <a class="und" href="event?e=79854&amp;f=ST">Pro Tour Lorwyn Eclipsed (Richmond, VA)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">31/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79785&amp;f=ST">Champions Cup Special Qualifier</a> @ <a class="und" href="event?e=79785&amp;f=ST">Kawasaki (Japan)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">30/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79746&amp;f=ST">Pro Tour Lorwyn Eclipsed</a> @ <a class="und" href="event?e=79746&amp;f=ST">Richmond</a></td>
 <td align="center" width="13%"><img height="20" src="/graph/bigstar.png"/></td>
 <td align="right" class="S12" width="12%">30/01/26</td>
 </tr>
 </table>,
 <table align="center" border="0" class="Stable" width="98%">
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79745&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">30/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79719&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">30/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79671&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">29/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79666&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">27/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79651&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">26/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79664&amp;f=ST">Saturday ReCQ #2</a> @ <a class="und" href="event?e=79664&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79600&amp;f=ST">Super Sunday RCQ #2</a> @ <a class="und" href="event?e=79600&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79599&amp;f=ST">Super Sunday RCQ #1</a> @ <a class="und" href="event?e=79599&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtga.png" title="MTG Arena"/></td>
 <td class="S14" width="70%"><a href="event?e=79598&amp;f=ST">Izzet Explosive Experiment Event</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79563&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79462&amp;f=ST">Regional Championship</a> @ <a class="und" href="event?e=79462&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">25/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79569&amp;f=ST">Saturday RCQ</a> @ <a class="und" href="event?e=79569&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79482&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79476&amp;f=ST">MTGO Challenge 32</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79428&amp;f=ST">RCQ</a> @ <a class="und" href="event?e=79428&amp;f=ST">BB-Spiele (Rosenheim, Germany)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79391&amp;f=ST">RCQ</a> @ <a class="und" href="event?e=79391&amp;f=ST">Back to Games (Dubai, UAE)</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">24/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79568&amp;f=ST">Friday Standard LCQ #16</a> @ <a class="und" href="event?e=79568&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79567&amp;f=ST">Friday Standard LCQ #15</a> @ <a class="und" href="event?e=79567&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79566&amp;f=ST">Friday Standard LCQ #14</a> @ <a class="und" href="event?e=79566&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="14" src="/graph/online/mtgo.png" title="MTG Online"/></td>
 <td class="S14" width="70%"><a href="event?e=79523&amp;f=ST">MTGO Challenge 64</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 </table>,
 <table align="center" border="0" class="Stable" width="98%">
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79453&amp;f=ST">Friday Standard LCQ #13</a> @ <a class="und" href="event?e=79453&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79450&amp;f=ST">Friday Standard LCQ #12</a> @ <a class="und" href="event?e=79450&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79451&amp;f=ST">Friday Standard LCQ #11</a> @ <a class="und" href="event?e=79451&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79455&amp;f=ST">Friday Standard LCQ #10</a> @ <a class="und" href="event?e=79455&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79448&amp;f=ST">Friday Standard LCQ #9</a> @ <a class="und" href="event?e=79448&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79457&amp;f=ST">Friday Standard LCQ #8</a> @ <a class="und" href="event?e=79457&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79447&amp;f=ST">Friday Standard LCQ #7</a> @ <a class="und" href="event?e=79447&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">
 <td align="center" width="5%"><img height="17" src="/graph/online/paper.png" title="Paper"/></td>
 <td class="S14" width="70%"><a href="event?e=79446&amp;f=ST">Friday Standard LCQ #6</a> @ <a class="und" href="event?e=79446&amp;f=ST">SCG CON Portland</a></td>
 <td align="center" width="13%"><img src="/graph/star.png"/><img src="/graph/star.png"/></td>
 <td align="right" class="S12" width="12%">23/01/26</td>
 </tr>
 <tr class="hover_tr">

Now that we have the html for all tournaments tables, we need to extract the following information:
- tournament name
- tournament date
- link to tournament information

In [5]:
names = []
dates = []
links = []
for tournaments_table in tournaments_tables:
    # get event names and dates
    table_text = tournaments_table.get_text()
    name_dates = re.split("\\n{3,4}|\\n{2}", table_text)[1:]
    names.extend(name_dates[:-1:2])
    dates.extend(name_dates[1::2])

    # get event links
    table_hrefs = re.findall("<a href=.+?>", str(tournaments_table))
    links.extend([re.split("\"", str(table_href))[1] for table_href in table_hrefs])
#
all_tournaments_df = pd.DataFrame({'Name': names, 'Date': dates, 'Link': links})
all_tournaments_df["Date"] = pd.to_datetime(all_tournaments_df["Date"], format="%d/%m/%y")
display(all_tournaments_df, all_tournaments_df.dtypes)

,Name,Date,Link
0,MTGO Challenge 32 NEW,2026-02-13,event?e=80372&amp;f=ST
1,MTGO Challenge 32 NEW,2026-02-12,event?e=80328&amp;f=ST
2,MTGO Challenge 32 NEW,2026-02-10,event?e=80293&amp;f=ST
3,MTGO Challenge 64,2026-02-09,event?e=80250&amp;f=ST
4,MTGO Challenge 32,2026-02-08,event?e=80147&amp;f=ST
...,...,...,...
112,"RCQ @ SpellCrafter's Den (Upper Sandusky, OH)",2025-12-20,event?e=78209&amp;f=ST
113,"Champions Cup Special Qualifier @ TC (Osaka, J...",2025-12-20,event?e=78207&amp;f=ST
114,MTGO Challenge 32,2025-12-20,event?e=78173&amp;f=ST
115,MTGO Challenge 32,2025-12-20,event?e=78134&amp;f=ST
116,MTGO Challenge 32,2025-12-19,event?e=78105&amp;f=ST

Name               str
Date    datetime64[us]
Link               str
dtype: object

The dataframe above has *all* large tournaments in the last two months. Some of these tournaments include Magic: The Gathering games played online in the app which has an alternative system for pricing cards. Due to this we want to only look at tournaments played outside of the app. 

Thankfully, these tournaments are denoted with "MTGO" so we can filter the `Name` property of the `tournaments_df` to only include tournaments without "MTGO" in the name. 

Also, we are only concerned with tournaments in January 2026, so we'll filter tournaments from before or after that time out as well. 

Lastly, the `Link` contains only the suffix of the URL. We need to append the base URL (mtgtop8.com) to this.

In [11]:
# all tournaments that are not online (i.e., do not include "MTGO")
not_online = ~all_tournaments_df["Name"].str.contains("MTGO")

# all tournaments in january
in_january = (all_tournaments_df["Date"] >= '2026-01-01') & (all_tournaments_df["Date"] < '2026-02-01')

tournaments_df = all_tournaments_df[not_online & in_january].reset_index(drop=True)

# adding base_url to links
base_url = "https://mtgtop8.com"
tournaments_df["Link"] = base_url + '/' + tournaments_df["Link"]

tournaments_df

,Name,Date,Link
0,2nd Chance PTQ @ Pro Tour Lorwyn Eclipsed (Ric...,2026-01-31,https://mtgtop8.com/event?e=79854&amp;f=ST
1,Champions Cup Special Qualifier @ Kawasaki (Ja...,2026-01-30,https://mtgtop8.com/event?e=79785&amp;f=ST
2,Pro Tour Lorwyn Eclipsed @ Richmond,2026-01-30,https://mtgtop8.com/event?e=79746&amp;f=ST
3,Saturday ReCQ #2 @ SCG CON Portland,2026-01-25,https://mtgtop8.com/event?e=79664&amp;f=ST
4,Super Sunday RCQ #2 @ SCG CON Portland,2026-01-25,https://mtgtop8.com/event?e=79600&amp;f=ST
5,Super Sunday RCQ #1 @ SCG CON Portland,2026-01-25,https://mtgtop8.com/event?e=79599&amp;f=ST
6,Izzet Explosive Experiment Event,2026-01-25,https://mtgtop8.com/event?e=79598&amp;f=ST
7,Regional Championship @ SCG CON Portland,2026-01-25,https://mtgtop8.com/event?e=79462&amp;f=ST
8,Saturday RCQ @ SCG CON Portland,2026-01-24,https://mtgtop8.com/event?e=79569&amp;f=ST
9,"RCQ @ BB-Spiele (Rosenheim, Germany)",2026-01-24,https://mtgtop8.com/event?e=79428&amp;f=ST
10,"RCQ @ Back to Games (Dubai, UAE)",2026-01-24,https://mtgtop8.com/event?e=79391&amp;f=ST
11,Friday Standard LCQ #16 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79568&amp;f=ST
12,Friday Standard LCQ #15 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79567&amp;f=ST
13,Friday Standard LCQ #14 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79566&amp;f=ST
14,Friday Standard LCQ #13 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79453&amp;f=ST
15,Friday Standard LCQ #12 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79450&amp;f=ST
16,Friday Standard LCQ #11 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79451&amp;f=ST
17,Friday Standard LCQ #10 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79455&amp;f=ST
18,Friday Standard LCQ #9 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79448&amp;f=ST
19,Friday Standard LCQ #8 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79457&amp;f=ST
20,Friday Standard LCQ #7 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79447&amp;f=ST
21,Friday Standard LCQ #6 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79446&amp;f=ST
22,Friday Standard LCQ #5 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79456&amp;f=ST
23,Friday Standard LCQ #4 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79445&amp;f=ST
24,Friday Standard LCQ #3 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79452&amp;f=ST
25,Friday Standard LCQ #2 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79449&amp;f=ST
26,Friday Standard LCQ #1 @ SCG CON Portland,2026-01-23,https://mtgtop8.com/event?e=79454&amp;f=ST
27,Champions Cup Season Special Qualifier @ Kawas...,2026-01-23,https://mtgtop8.com/event?e=79458&amp;f=ST
28,Super Sunday RCQ @ SCG CON Atlanta,2026-01-11,https://mtgtop8.com/event?e=78984&amp;f=ST
29,Sunday ReCQ @ SCG CON Atlanta,2026-01-11,https://mtgtop8.com/event?e=78983&amp;f=ST
30,Sunday Destination Qualifier - Fanfinity @ Spo...,2026-01-11,https://mtgtop8.com/event?e=78947&amp;f=ST
31,"RCQ @ Il Labirinto (Bollate, Milan)",2026-01-11,https://mtgtop8.com/event?e=78848&amp;f=ST
32,Saturday ReCQ @ SCG CON Atlanta,2026-01-10,https://mtgtop8.com/event?e=78912&amp;f=ST
33,Magic Spotlight: The Avatar @ SCG CON Atlanta,2026-01-10,https://mtgtop8.com/event?e=78892&amp;f=ST
34,Main Event - Magic Spotlight Series - Fanfinit...,2026-01-10,https://mtgtop8.com/event?e=78891&amp;f=ST
35,Champions Cup Special Qualifier @ Kawasaki (Ja...,2026-01-09,https://mtgtop8.com/event?e=78890&amp;f=ST
36,Friday ReCQ #3 @ SCG CON Atlanta,2026-01-09,https://mtgtop8.com/event?e=78852&amp;f=ST
37,Friday ReCQ #2 @ SCG CON Atlanta,2026-01-09,https://mtgtop8.com/event?e=78850&amp;f=ST
38,Friday ReCQ #1 @ SCG CON Atlanta,2026-01-09,https://mtgtop8.com/event?e=78849&amp;f=ST
39,FullFire/GYDO Invitational 1K,2026-01-04,https://mtgtop8.com/event?e=78679&amp;f=ST
40,"RCQ @ Cardboard Horde (Sidney, OH)",2026-01-04,https://mtgtop8.com/event?e=78668&amp;f=ST
41,"RCQ @ Boardwalk Games (Carrollton, TX)",2026-01-03,https://mtgtop8.com/event?e=78728&amp;f=ST
42,"RCQ @ BB-Spiele (Rosenheim, Germany)",2026-01-03,https://mtgtop8.com/event?e=78607&amp;f=ST
43,"RCQ @ Tier 1 Games (Kokomo, IN)",2026-01-03,https://mtgtop8.com/event?e=78576&amp;f=ST
44,Champions Cup Special Qualifier @ Nagoya (Japan),2026-01-01,https://mtgtop8.com/event?e=78554&amp;f=ST

All in all, we're left with 44 tournaments to grab decks for!

# Getting Decklists for Each Tournament

## Test

In [12]:
r = requests.get("https://mtgtop8.com/event?e=79854&amp;f=ST")
print(r.status_code)

200

In [27]:
soup = BeautifulSoup(r.content)
# print(soup.prettify())
# soup.find_all("div", class_="chosen_tr")
test = soup.find_all("a", class_="player")
for t in test:
    display(t.get_text())

'Collins Mullen'

'Edgar Magalhaes'

'Guiyote'

'Thomas Mechin'

'Ondrej Strasky'

'David Ĺberg'

'Josh Moscoe'

'Ryan Bellamy'

'Peter Yeh'

'Trevor Sharp'

'Keithcapstick'

'Sebastian Sachse'

'Ian Starkebaum'

'James Newman'

'David Gonzalez Romero "playmobil"'

'Steven Browne'

In [42]:
# you can either do this and try to filter down with regex via tags or do the commented method
test = re.findall("<a href=\"\?e=79854.+?>.+?</a>", str(soup)) # or <a href=\"\?e=79854.+?>[^<|>]+</a>
test

<>:2: SyntaxWarning: invalid escape sequence '\?'
<>:2: SyntaxWarning: invalid escape sequence '\?'
/var/folders/mc/k7dtvknn215g0s76b8mlhf_r0000gp/T/ipykernel_35854/4140714637.py:2: SyntaxWarning: invalid escape sequence '\?'
  test = re.findall("<a href=\"\?e=79854.+?>.+?</a>", str(soup)) # or <a href=\"\?e=79854.+?>[^<|>]+</a>

['<a href="?e=79854&amp;d=806938&amp;f=ST"><img src="/metas_thumbs/808.jpg"/></a>',
 '<a href="?e=79854&amp;d=806938&amp;f=ST">Temur Full Bore Harmonizer </a>',
 '<a href="?e=79854&amp;d=806939&amp;f=ST"><img src="/metas_thumbs/13.jpg"/></a>',
 '<a href="?e=79854&amp;d=806939&amp;f=ST">Dimir Control</a>',
 '<a href="?e=79854&amp;d=806941&amp;f=ST"><img src="/metas_thumbs/2843.jpg"/></a>',
 '<a href="?e=79854&amp;d=806941&amp;f=ST">Bant Airbending</a>',
 '<a href="?e=79854&amp;d=806940&amp;f=ST"><img src="/metas_thumbs/15.jpg"/></a>',
 '<a href="?e=79854&amp;d=806940&amp;f=ST">Izzet Spellementals</a>',
 '<a href="?e=79854&amp;d=806942&amp;f=ST"><img src="/metas_thumbs/15.jpg"/></a>',
 '<a href="?e=79854&amp;d=806942&amp;f=ST">Izzet Lesson</a>',
 '<a href="?e=79854&amp;d=806945&amp;f=ST"><img src="/metas_thumbs/15.jpg"/></a>',
 '<a href="?e=79854&amp;d=806945&amp;f=ST">Izzet Lesson</a>',
 '<a href="?e=79854&amp;d=806943&amp;f=ST"><img src="/metas_thumbs/832.jpg"/></a>',
 '<a href="?e=79854&amp;d=806943&amp;f=ST">Simic Nature\'s Rhythm</a>',
 '<a href="?e=79854&amp;d=806944&amp;f=ST"><img src="/metas_thumbs/808.jpg"/></a>',
 '<a href="?e=79854&amp;d=806944&amp;f=ST">Temur Full Bore Harmonizer </a>',
 '<a href="?e=79854&amp;d=806952&amp;f=ST"><img src="/metas_thumbs/296.jpg"/></a>',
 '<a href="?e=79854&amp;d=806952&amp;f=ST">Elementals</a>',
 '<a href="?e=79854&amp;d=806951&amp;f=ST"><img src="/metas_thumbs/15.jpg"/></a>',
 '<a href="?e=79854&amp;d=806951&amp;f=ST">Izzet Lesson</a>',
 '<a href="?e=79854&amp;d=806950&amp;f=ST"><img src="/metas_thumbs/15.jpg"/></a>',
 '<a href="?e=79854&amp;d=806950&amp;f=ST">Izzet Spellementals</a>',
 '<a href="?e=79854&amp;d=806953&amp;f=ST"><img src="/metas_thumbs/263.jpg"/></a>',
 '<a href="?e=79854&amp;d=806953&amp;f=ST">Mono Green Landfall</a>',
 '<a href="?e=79854&amp;d=806947&amp;f=ST"><img src="/metas_thumbs/150.jpg"/></a>',
 '<a href="?e=79854&amp;d=806947&amp;f=ST">Selesnya Aggro</a>',
 '<a href="?e=79854&amp;d=806946&amp;f=ST"><img src="/metas_thumbs/832.jpg"/></a>',
 '<a href="?e=79854&amp;d=806946&amp;f=ST">Simic Nature\'s Rhythm</a>',
 '<a href="?e=79854&amp;d=806949&amp;f=ST"><img src="/metas_thumbs/227.jpg"/></a>',
 '<a href="?e=79854&amp;d=806949&amp;f=ST">Superior Doomsday </a>',
 '<a href="?e=79854&amp;d=806948&amp;f=ST"><img src="/metas_thumbs/227.jpg"/></a>',
 '<a href="?e=79854&amp;d=806948&amp;f=ST">Superior Reanimator</a>',
 '<a href="?e=79854&amp;d=806938&amp;f=ST&amp;switch=visual">Switch to Visual</a>',
 '<a href="?e=79854&amp;d=806938&amp;f=ST&amp;switch_o=omenpaths"><img src="/graph/omenpaths/to_om.png" style="height:20px;" title="Switch to Through the Omenpaths cards"/></a>']

# Some Statistics (3-5)

# Some Viz

Only base card price. Foil etc prices are for looks and not for usability. base card price is only about usability.